### ISSUE TITLE
Syntax is wrong for color backgrounds

### ISSUE THREAD

**Issue by mrmanc** [dploeger/jekyll-revealjs#17]
I made a mistake in #14 when I wrote the replace code for background tags. I should have used `<background>` and `</background>` but I used `<background/>` by mistake. I’ll get a PR raised to resolve at some point. Hopefully, people agree that `</background>` makes more sense to close the colour definition. I can either do this backwards-compatible or not.

**Comment by dploeger** [comment]
I see this as a typo bug and we don't need to be backwards-compatible about it. I'd be happy to accept the PR.

**Comment by mrmanc** [comment]
Apolologies—I’ve just noticed I haven’t resolved this yet. I’ll assign myself and try to get a fix in soon.

**Comment by dploeger** [comment]
Thanks. 👍

**Comment by infotexture** [comment]
@mrmanc Any plans to resolve this soon? — _Happy to send a PR if you don't have time…_

**Comment by dploeger** [comment]
@infotexture Please do, thanks. I'm not actively developing this anymore, but am open to merge pull request and release new versions
