### ISSUE TITLE
Description and author are not configurable

### ISSUE THREAD

**Issue by mrmanc** [dploeger/jekyll-revealjs#18]
I just noticed that the description and author are hard-coded in the layout. I’m guessing you’d be open to a change which made this configurable? Otherwise services like Slack will present the reveal.js tagline rather than something related to the presentation in the snippet alongside a link.

**Comment by dploeger** [comment]
Yes, very open. This was just not in the focus. Thanks! 🎁

**Comment by infotexture** [comment]
This would be a welcome change indeed. 👍 

Regarding the layout file, I noticed there's quite a mix of spaces & tabs in `_layouts/reveal.html` and considered normalizing that, but not sure how closely this tracks an upstream `reveal.js` template and didn't want to complicate future diffing. 🤔

**Comment by mrmanc** [comment]
I’m on as we speak 😂About to push and PR, but don’t want to step on your feet. Good spot on the whitespace… I’ve just replaced all the spaces with tabs as per what looks like the [original file](https://github.com/hakimel/reveal.js/blob/master/index.html).

**Comment by infotexture** [comment]
👍 Go for it. Hadn't touched it to prevent conflicts.
