### ISSUE TITLE
Updating reveal.js directory to latest commit fails

### ISSUE THREAD

**Issue by kyleskrinak** [dploeger/jekyll-revealjs#2]
Thank you for a great reveal.js slide builder. I've been using this for several months now. If I follow your instructions, I can create a reveal-based slideshow without error. However, I notice the reveal.js directory is out-of-date. To address this, I successfully updated the reveal.js directory from the sha it's pointing to, 8b8cc60 to the latest (as of today), ce8ea84. I then ran the default reveal.js grunt task to prep the reveal.js directory, and added head.min.js from http://headjs.com/site/download.html into reveal.js/lib/js directory and tried to start `jekyll s` However, after doing so, I am seeing this error; `jekyll 2.5.3 | Error:  user lambdas.json doesn't exist`

This [ticket](https://github.com/jekyll/jekyll/issues/3405#issuecomment-72791021) which seems related, suggests adding "exclude: [vendor]" to _config.yaml, but that hasn't helped. I'm guessing this is related to the mustache node module, but I am unclear as to what to try next.

**Comment by dploeger** [comment]
Thanks for the info. I've just updated jekyll-reveal.js to 1.1, which is compatible with reveal.js 3.0.0

**Comment by kyleskrinak** [comment]
Fantastic — much thanks.
