### ISSUE TITLE
Publish slides as github pages site

### ISSUE THREAD

**Issue by mrmanc** [dploeger/jekyll-revealjs#38]
I think it would be good to provide a working demo of the slides by changing GitHub Pages to publish the root of `master`. Currently, the `gh-pages` branch is used and contains an automatically generated site which doesn’t show off the capability.

I can’t change this myself, I think it is one for @dploeger.

**Comment by mrmanc** [comment]
Feel free to make me a repo admin if you’d like me to resolve this myself 😃

**Comment by dploeger** [comment]
Apparently I can't make you a repo admin. At least I don't find the option. But I changed the pages configuration to master.

**Comment by mrmanc** [comment]
Awesome, thanks for that! 🎉
