### ISSUE TITLE
Suggestion: Use collections instead of posts

### ISSUE THREAD

**Issue by tamouse** [dploeger/jekyll-revealjs#6]
The new collections seems ideal for using in a slide deck. :) Thanks for putting this together.

**Comment by TomK32** [comment]
I've just started to try this in my own github page, will report back with a pull request :D

**Comment by tamouse** [comment]
Awesome, @TomK32  -- I've been using collections in my past few slide sets; I really need to update this

**Comment by dploeger** [comment]
This issue seems to have slipped and I am currently revisiting this code to include a proper versioning and release scheme.

So, @tamouse and @TomK32 is this issue still valid? If so, please elaborate on what you would like, because I didn't get that. 😄

**Comment by tamouse** [comment]
I've mostly stopped using jekyll for presentations, anymore, but my thoughts were along the lines that since in the modern jekyll implementation, `_posts` are just another collection, you could use collections for the slides, and have multi-part slide shows. I was mostly thinking of this for some classes I teach that go over multiple days (like 3 evening sessions).

I don't think there's anything that needs to be done especially to support this. I don't know if this is a relevant issue in the sense of creating any changes to this repo, I believe it's just something that jekyll will let you do out of the box.

**Comment by dploeger** [comment]
Okay, I think, that this is supported with this code, too. So I'll close this issue.
