### ISSUE TITLE
Support GitHub Pages

### ISSUE THREAD

**Issue by shibasisp** [dploeger/jekyll-revealjs#7]
When I tried to make a presentation using jekyll-revealjs,  it worked fine locally but after pushing it to github, it says

> " Your site is having problems building: The tag fragment on line 3 in _posts/1-1-1-3-how_to_examine.md is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error."

**Comment by dploeger** [comment]
Do you want to publish the presentation to github pages or does this happen on a commit to a normal branch?

**Comment by shibasisp** [comment]
I am trying to publish it to github pages.

**Comment by dploeger** [comment]
Ah, okay. I haven't tried that. Maybe we need to make some adjustments to make it available to github pages.

**Comment by dploeger** [comment]
I'm filing this issue as an enhancement to support github pages now.

**Comment by shibasisp** [comment]
As I see, the example presentation you provided is working great. I suspect the problem is because of the few changes from jekyll2 to jekyll3.

**Comment by dploeger** [comment]
Hmm... I tried running the sample presentation with jekyll3 without any problems. Could you perhaps provide me with your presentation?

**Comment by pganssle** [comment]
I also had this problem, by the way. I got the impression was that I was using fragments in my presentation, and github has a whitelist of plugins (and the _plugins folder of the current directory is not on it). Presumably this is because GH doesn't want to execute arbitrary Ruby code on their platform.

**Comment by mrmanc** [comment]
I noticed this problem trying to publish to GitHub Pages. As @pganssle says, it’s due to the custom plugins in this project. I resolved it by removing the [extra two plugins](https://github.com/dploeger/jekyll-revealjs/tree/master/_plugins) and references to them from my fork.

**Comment by dploeger** [comment]
Oh, okay. Do you guys know about a way to whitelist them or another way to support custom backgrounds and reveal.js fragments?

**Comment by dploeger** [comment]
Thanks for the analysis, btw.

**Comment by mrmanc** [comment]
I think to get the plugins whitelisted you’d need to speak to GitHub to convince them of the merit of adding that plugin to every pages site. Since this is such a specific thing and so small, I can’t imagine that would be successful. I was wondering whether it would be better to support fragments and backgrounds using the Jekyll include mechanism instead of Liquid custom tags? That way code like this

```
It's also possible to do fragments.

- Like {% fragment %}
- This {% fragment %}
```

would instead look like this:

```

```
It's also possible to do fragments.

- Like {% include fragment.html %}
- This {% include fragment.html %}
```

And you’d have a file named `fragment.html` in `_includes` containing simply `<!-- .element: class=\"fragment\" -->` from what I can determine.

> Thanks for the analysis, btw.

You’re welcome :)

**Comment by mrmanc** [comment]
Incidentally, totally happy to provide a PR for this.

**Comment by dploeger** [comment]
Great! Please do. We could support both so we don't have to deprecate older installations but can support GitHub Pages as well.

**Comment by mrmanc** [comment]
Ready to go on the fragment version, but would you prefer I leave the tag version in too? Might be confusing to have two styles…

**Comment by dploeger** [comment]
I'd like to, yes. We might deprecate the tag version in the docs, but I don't want to remove it just yet to not break other installations.

**Comment by pganssle** [comment]
TBH the tag version is much cleaner, so for people *not* deploying to GH Pages, it makes sense to keep it around.

**Comment by mrmanc** [comment]
Cool, that’s a great point. I’ll leave it out of the docs but still there in the plugins. That won’t cause any problems with GHP.

**Comment by dploeger** [comment]
Hm. Then I'd vote for including *both* into the docs. So the default way would be the plugins with a special note about GH pages and the include-method.

@mrmanc If you'd agree, could you please add that to #14?

**Comment by dploeger** [comment]
I guess, it's only a documentation issue. We just need a special chapter on the docs about using this with Github pages. So the usual code would be mostly untouched and the chapter details out the usage on GH Pages.

**Comment by mrmanc** [comment]
Updated docs here: <https://github.com/autotraderuk/jekyll-revealjs/tree/fragments-and-background-includes#fragments>

@dploeger Would you prefer the GHP variations are gathered in one location instead?

**Comment by dploeger** [comment]
@mrmanc Doesn't GHP require you to also remove the _plugins directory? If that's not necessary, then you can just leave it there!

**Comment by pganssle** [comment]
@mrmanc I like that! I personally like the HTML-like syntax, but I wonder if the bracket syntax is less likely to cause overlap with real HTML tags.

Do you know how to escape those tags? Just HTML entity codes like &lt;fragment/&rt;?

**Comment by mrmanc** [comment]
> @mrmanc I like that! I personally like the HTML-like syntax

Oh, great—thanks Paul :)

> I wonder if the bracket syntax is less likely to cause overlap with real HTML tags.

As soon as the filter kicks in they’ll disappear so the only weirdness for me is that the user might think they are actually HTML. At least the square bracket version is clearly not an HTML syntax (which provides a clue that it’s going to get processed into something else). I’m not fussed either way though.

> Do you know how to escape those tags? Just HTML entity codes like &lt;fragment/&gt;?

I’m not sure what you mean. Why would they need to be escaped? The filter just takes the `<fragment/>` string and replaces it with `<!-- .element: class=\"fragment\" -->` (which reveal.js understands). There shouldn’t be any need for anything to be escaped.

**Comment by pganssle** [comment]
@mrmanc I guess I mean what if you want to write the literal string `<fragment/>` not in a code or pre block? It seems unlikely, I'm just curious.

**Comment by dploeger** [comment]
I'd also like one solution for both better. We do need to deprecate (and thus support for the current version at least) the other method as well.

**Comment by dploeger** [comment]
Just created a version 1.4 out of your last changes, @pganssle, as a preliminary work for including this in version 1.5.

In version 2.0.0 (finally semver, yay!) we can remove the old options.

I never thought, this code would get any attention, so I haven't really planned for a proper release scheme. 🤣 

Thanks to you both for your work and comments.

**Comment by mrmanc** [comment]
> @mrmanc I guess I mean what if you want to write the literal string <fragment/> not in a code or pre block? It seems unlikely, I'm just curious.

Ahhhh, gotcha. Thanks, I think I’d just written that off as it’s so unlikely. Yes, `&lt;fragment/&gt;` renders absolutely fine, as does `` `<fragment/>` `` (i.e. in an inline code block).

**Comment by mrmanc** [comment]
I’ve pushed a change in #14 to use a filter and removed the includes. I went with the HTML like syntax, but this is easily changeable.

I’ve moved the index code into the layout as part of this change.

**Comment by dploeger** [comment]
Last question, just to be sure: That change doesn't remove the current implementation with the plugins, right? So you can still use both.

**Comment by mrmanc** [comment]
Yep, that’s correct. The plugins still exist in the [branch on our fork](https://github.com/autotraderuk/jekyll-revealjs/tree/fragments-and-background-includes/_plugins). Any existing use will continue to work, but the plugins as a feature are not advertised in the docs. You can still use both :)

**Comment by mrmanc** [comment]
I should add that moving the code from `index.html` into the layout means that any customisations made in `index.html` files will not apply any more. I haven’t included content from those pages in the layout since this would cause the content to appear twice in forked versions of this repo. So repositories with content in the `index.html` file will continue to work, but any changes they’ve made to that file will not take any effect. This felt like a fair trade-off for moving the logic around displaying and formatting slides into the layout, as this brings it into what is considered part of the theme, and is thus version controlled when using the theme remotely.

**Comment by dploeger** [comment]
Yes, I saw that, but I understand, that it's better that way. I guess, we have to live with that. Thanks for your work. I will merge that now.

**Comment by mrmanc** [comment]
Awesome, really pleased to get this merged in :) Thanks for all the feedback @dploeger and @pganssle!
