### ISSUE TITLE
Italic conflicts with fragments

### ISSUE THREAD

**Issue by Aubreymcfato** [dploeger/jekyll-revealjs#8]
For example, if in one slide I have:

```
Item one.  <!-- .element: class="fragment" data-fragment-index="1" -->

Item *two*.  <!-- .element: class="fragment" data-fragment-index="2" -->

```
the word "Item"  of element "Item *two*" will not respect the order of appearance, and will be shown regardless.

**Comment by dploeger** [comment]
This actually is a problem with reveal.js. I've opened hakimel/reveal.js#1848 for you. Please watch that issue.
